Repository Cr0ssEyE/Project_LLL, pull requests merged in 2024-03, with the labels that each got.

#58 [#52] FMOD 테스트용 브랜치 병합 요청
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/DataAsset/DA_Player.uasset
  Content/Entity/Characters/Monster/MeleeMonster/Orawave/Animations/Melee_Run_Forward.uasset
  Content/Entity/Characters/Monster/RangedMonster/EnergyBlaster/Animations/Sequences/AS_Range_Walk.uasset
  Content/Entity/Characters/Monster/RangedMonster/EnergyBlaster/Animations/Sequences/AS_Ranged_Run.uasset
  Content/Entity/Characters/Player/Animations/Sequences/AS_Paladin_Run.uasset
  Content/Entity/Characters/Player/Animations/Sequences/AS_Paladin_Slide.uasset
  Content/Entity/Characters/Player/Animations/Sequences/AS_Paladin_Walk.uasset
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
  Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacter.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
  Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerBase.cpp
  Source/Project_LLL/Private/GAS/Cue/LLL_GC_Base.cpp
  Source/Project_LLL/Public/Entity/Character/Base/LLL_BaseCharacter.h
  Source/Project_LLL/Public/Entity/Character/Monster/Base/LLL_MonsterBase.h
  Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerBase.h
  Source/Project_LLL/Public/GAS/Cue/LLL_GC_Base.h
Labels: documentation, materialization

#67 [#66] 몬스터 애니메이션 관련 버그 수정
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
  Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacter.cpp
Labels: hotfix

#69 [#68]몬스터 로직 개선
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Config/DefaultEngine.ini
  Config/DefaultGameplayTags.ini
  Content/Blueprints/TestEnergyBlaster.uasset
  Content/Entity/Characters/Monster/BB_MonsterBase.uasset
  Content/Entity/Characters/Monster/BT_MonsterBase.uasset
  Content/Entity/Characters/Monster/MeleeMonster/Orawave/Animations/Montage/AM_DummyMelee_Attack.uasset
  Content/Entity/Characters/Monster/RangedMonster/EnergyBlaster/Animations/Montage/AM_DummyRangedAttack.uasset
  Content/GAS/Abilities/Monster/MeleeMonster/Orawave/BPGA_OrawaveAttackHit.uasset
  Content/GAS/Abilities/Monster/MeleeMonster/Orawave/BPGA_OrawaveGroundStrike.uasset
  Content/GAS/Abilities/Monster/RangedMonster/EnergyBlaster/BPGA_EnergyBlasterSpawnThrownObject.uasset
  Content/Level/PrototypeLevel.umap
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
  Source/Project_LLL/Private/BT/LLL_DetectPlayer_BTService.cpp
  Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacter.cpp
  Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacterUIManager.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBaseAIController.cpp
  Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerBase.cpp
  Source/Project_LLL/Private/Entity/Object/Thrown/LLL_ThrownObject.cpp
  Source/Project_LLL/Private/GAS/Ability/Monster/LLL_MGA_GroundStrike.cpp
  Source/Project_LLL/Private/GAS/Attribute/LLL_CharacterAttributeSetBase.cpp
  Source/Project_LLL/Private/Interface/LLL_ObjectPoolingObjectInterface.cpp
  Source/Project_LLL/Public/BT/LLL_DetectPlayer_BTService.h
  Source/Project_LLL/Public/Constant/LLL_BlackBoardKeyNames.h
  Source/Project_LLL/Public/Constant/LLL_CollisionChannel.h
  Source/Project_LLL/Public/DataAsset/LLL_BaseObjectDataAsset.h
  Source/Project_LLL/Public/Entity/Character/Base/LLL_BaseCharacter.h
  Source/Project_LLL/Public/Entity/Character/Monster/Base/LLL_MonsterBaseAIController.h
  Source/Project_LLL/Public/Entity/Object/Thrown/LLL_ThrownObject.h
  Source/Project_LLL/Public/GAS/Ability/Monster/LLL_MGA_GroundStrike.h
  Source/Project_LLL/Public/Interface/LLL_ObjectPoolingObjectInterface.h
Labels: enhancement, hotfix

#71 [#70] 버그 핫픽스
  Binaries/Win64/Project_LLLEditor.target
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Melee/LLL_MeleeMonster.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Melee/Orawave/LLL_Orawave.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Ranged/EnergyBlaster/LLL_EnergyBlaster.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Ranged/LLL_RangedMonster.cpp
  Source/Project_LLL/Public/Entity/Character/Monster/Melee/Orawave/LLL_Orawave.h
  Source/Project_LLL/Public/Entity/Character/Monster/Ranged/EnergyBlaster/LLL_EnergyBlaster.h
Labels: bug, hotfix

#75 [#72]AI 퍼셉션(Sight) 연구
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Config/DefaultEngine.ini
  Content/Blueprints/System/BP_MonsterSpawner.uasset
  Content/Entity/Characters/Monster/BT_MonsterBase.uasset
  Content/GAS/Cues/Sounds/BPGC_Player_Step.uasset
  Content/Level/PrototypeLevel.umap
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
  Source/Project_LLL/Private/BT/LLL_CheckRange_BTService.cpp
  Source/Project_LLL/Private/BT/LLL_DetectPlayer_BTService.cpp
  Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacter.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBaseAIController.cpp
  Source/Project_LLL/Private/System/MonsterSpawner/LLL_MonsterSpawner.cpp
  Source/Project_LLL/Public/BT/LLL_CheckRange_BTService.h
  Source/Project_LLL/Public/BT/LLL_DetectPlayer_BTService.h
  Source/Project_LLL/Public/Entity/Character/Monster/Base/LLL_MonsterBaseAIController.h
  Source/Project_LLL/Public/System/MonsterSpawner/LLL_MonsterSpawner.h
Labels: documentation, enhancement
