Repository Cr0ssEyE/Project_LLL, pull requests merged in 2024-05, with the labels that each got.

#132 [#131] FMOD 버전 이슈 해결, 플레이어 스폰포인트 이슈 해결, 대쉬 로직 개선
  Binaries/Win64/Project_LLLEditor.target
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/StarterContent/Architecture/Floor_400x400.uasset
  Plugins/ActorLocker/Binaries/Win64/UnrealEditor-ActorLocker.dll
  Plugins/BlueprintRetarget/Binaries/Win64/UnrealEditor-BlueprintRetarget.dll
  Plugins/BlueprintRetarget/Source/BlueprintRetarget/Private/ContentBrowserExtensions.cpp
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
  Plugins/FMODStudio/Source/FMODAudioLink/Private/FMODAudioLinkInputClient.cpp
  Plugins/FMODStudio/Source/FMODStudio/Private/FMODAssetTable.h
  Plugins/FMODStudio/Source/FMODStudio/Private/FMODBlueprintStatics.cpp
  Plugins/FMODStudio/Source/FMODStudioEditor/Private/FMODStudioEditorModule.cpp
  Plugins/KawaiiPhysics/Binaries/Win64/UnrealEditor-KawaiiPhysics.dll
  Plugins/KawaiiPhysics/Binaries/Win64/UnrealEditor-KawaiiPhysicsEd.dll
  Plugins/LDAssistant/Binaries/Win64/UnrealEditor-LDAssistant.dll
  Source/Project_LLL.Target.cs
  Source/Project_LLL/Private/System/MapGimmick/LLL_MapGimmick.cpp
  Source/Project_LLL/Public/Util/LLL_MathHelper.h
  Source/Project_LLLEditor.Target.cs
Labels: enhancement, hotfix

#133 [#129] 어빌리티 개선
  Binaries/Win64/Project_LLLEditor.target
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/Blueprints/System/BP_RemoveAbilityTestActor.uasset
  Content/DataTable/AbilityDataTable.uasset
  Content/GAS/Abilities/Character/Player/RewardAbilitiesList/BPGA_FeatherStorm.uasset
  Content/GAS/Abilities/Character/Player/RewardAbilitiesList/BPGA_Player_Rush_Dummy.uasset
  Content/GAS/Abilities/Character/Player/RewardAbilitiesList/BPGA_Player_Test.uasset
  Content/GAS/Effects/Character/Player/RewardEffectsList/BPGE_FeatherStorm.uasset
  Content/GAS/Effects/Character/Player/RewardEffectsList/BPGE_GiveDummyAbility.uasset
  Content/Level/PrototypeLevel.umap
  Content/StarterContent/Architecture/Floor_400x400.uasset
  Plugins/ActorLocker/Binaries/Win64/UnrealEditor-ActorLocker.dll
  Plugins/BlueprintRetarget/Binaries/Win64/UnrealEditor-BlueprintRetarget.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
  Plugins/KawaiiPhysics/Binaries/Win64/UnrealEditor-KawaiiPhysics.dll
  Plugins/KawaiiPhysics/Binaries/Win64/UnrealEditor-KawaiiPhysicsEd.dll
  Plugins/LDAssistant/Binaries/Win64/UnrealEditor-LDAssistant.dll
  Source/Project_LLL/Private/GAS/Ability/Character/Player/LLL_PGA_Dash.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_FeatherStorm.cpp
  Source/Project_LLL/Private/Game/LLL_AbilityManageSubSystem.cpp
  Source/Project_LLL/Private/System/Reward/LLL_RewardGimmick.cpp
  Source/Project_LLL/Public/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_FeatherStorm.h
  Source/Project_LLL/Public/GAS/Effect/LLL_ExtendedGameplayEffect.h
Labels: enhancement

#137 [#136] ClawBasic 몬스터 구현
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Config/DefaultGameplayTags.ini
  Content/Blueprints/TextClawBasic.uasset
  Content/DataAsset/DA_ClawBasic.uasset
  Content/DataTable/MonsterSpawnData.uasset
  Content/Entity/Characters/Monster/BT_MonsterBase.uasset
  Content/Entity/Characters/Monster/BT_SwordDash.uasset
  Content/Entity/Characters/Monster/MeleeMonster/ClawBasic/Animations/ABP_ClawBasic.uasset
  Content/Entity/Characters/Monster/MeleeMonster/ClawBasic/Animations/Montages/AM_ClawBasic_Attack.uasset
  Content/Entity/Characters/Monster/MeleeMonster/ClawBasic/Animations/Montages/AM_ClawBasic_Charge.uasset
  Content/Entity/Characters/Monster/MeleeMonster/Orawave/Animations/ABP_Orawave.uasset
  Content/Entity/Characters/Monster/MeleeMonster/SwordDash/Animations/ABP_SwordDash.uasset
  Content/Entity/Characters/Monster/RangedMonster/EnergyBlaster/Animations/ABP_EnergyBlaster.uasset
  Content/Entity/Characters/Monster/RangedMonster/StaffBasic/Animations/ABP_StaffBasic.uasset
  Content/GAS/Abilities/Character/Monster/MeleeMonster/ClawBasic/BPGA_ClawBasic_Attack.uasset
  Content/GAS/Abilities/Character/Monster/MeleeMonster/ClawBasic/BPGA_ClawBasic_AttackHitCheck1.uasset
  Content/GAS/Abilities/Character/Monster/MeleeMonster/ClawBasic/BPGA_ClawBasic_AttackHitCheck2.uasset
  Content/GAS/Abilities/Character/Monster/MeleeMonster/ClawBasic/BPGA_ClawBasic_Charge.uasset
  Content/GAS/Effects/Character/Monster/MeleeMonster/ClawBasic/BPGE_ClawBasic_Attribute_Initialize.uasset
  Content/GAS/Effects/Character/Monster/MeleeMonster/ClawBasic/BPGE_ClawBasic_InflictDamage.uasset
  Content/GAS/Effects/Character/Monster/MeleeMonster/Orawave/BPGE_Orawave_Attribute_Initialize.uasset
  Content/GAS/Effects/Character/Monster/MeleeMonster/SwordDash/BPGE_SwordDash_Attribute_Initialize.uasset
  Content/GAS/TargetActors/Monster/MeleeMonster/ClawBasic/BPTA_ClawBasic_AttackTrace1.uasset
  Content/GAS/TargetActors/Monster/MeleeMonster/ClawBasic/BPTA_ClawBasic_AttackTrace2.uasset
  Content/Level/PrototypeLevel.umap
  Content/StarterContent/Architecture/Floor_400x400.uasset
  Plugins/BlueprintRetarget/Binaries/Win64/UnrealEditor-BlueprintRetarget.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
  Plugins/KawaiiPhysics/Binaries/Win64/UnrealEditor-KawaiiPhysics.dll
  Plugins/KawaiiPhysics/Binaries/Win64/UnrealEditor-KawaiiPhysicsEd.dll
  Plugins/LDAssistant/Binaries/Win64/UnrealEditor-LDAssistant.dll
  Source/Project_LLL/Private/DataAsset/LLL_ClawBasicDataAsset.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Melee/ClawBasic/LLL_ClawBasic.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Melee/ClawBasic/LLL_ClawBasicAIController.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Melee/ClawBasic/LLL_ClawBasicAnimInstance.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_FeatherStorm.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_Test.cpp
  Source/Project_LLL/Private/GAS/Attribute/Character/Monster/MeleeMonster/ClawBasic/LLL_ClawBasicAttributeSet.cpp
  Source/Project_LLL/Public/Constant/LLL_FilePath.h
  Source/Project_LLL/Public/DataAsset/LLL_ClawBasicDataAsset.h
  Source/Project_LLL/Public/Entity/Character/Monster/Melee/ClawBasic/LLL_ClawBasic.h
  Source/Project_LLL/Public/Entity/Character/Monster/Melee/ClawBasic/LLL_ClawBasicAIController.h
  Source/Project_LLL/Public/Entity/Character/Monster/Melee/ClawBasic/LLL_ClawBasicAnimInstance.h
  Source/Project_LLL/Public/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_Test.h
  Source/Project_LLL/Public/GAS/Attribute/Character/Monster/MeleeMonster/ClawBasic/LLL_ClawBasicAttributeSet.h
Labels: materialization

#147 [#144] 추격액션 리소스 사용 및 로직 개선, 넉백 로직 개선
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/DataAsset/DA_PlayerChaseHand.uasset
  Content/DataTable/AttributeInitializer/CT_PlayerData.uasset
  Content/Entity/Characters/Player/Animations/Montages/AS_PlayerCharacter_BaseAttack.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Animations/AS_DummyChaseHand_Grabbed.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Animations/AS_DummyChaseHand_Grabbed/Driving_AS_DummyChaseHand_Grabbed.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Animations/AS_DummyChaseHand_Throw.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Animations/AS_DummyChaseHand_Throw/Driving_AS_DummyChaseHand_Throw.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Animations/AS_Player_ChaseHand_Throw.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Animations/AS_Player_ChaseHand_Throw/Driving_AS_Player_ChaseHand_Throw.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Animations/AS_Player_ChaseHand_Throw/Driving_AS_Player_ChaseHand_Throw1.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Materials/MI_DummyChaseHand.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Materials/M_DummyChaseHand.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Meshes/PHYS_DummyChaseHand.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Meshes/PHYS_Player_ChaseHand.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Meshes/SKM_DummyChaseHand.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Meshes/SKM_Player_ChaseHand.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Meshes/SK_DummyChaseHand.uasset
  Content/Entity/Object/ThrownObject/ChaseHand/Meshes/SK_Player_ChaseHand.uasset
  Content/GAS/Abilities/Character/Player/ChaseHand/BPGA_Player_ChaseHand_Lock_Target.uasset
  Content/GAS/Abilities/Character/Player/ChaseHand/BPGA_Player_ChaseHand_Release_Move.uasset
  Content/GAS/Abilities/Character/Player/ChaseHand/BPGA_Player_ChaseHand_Release_Teleport.uasset
  Content/GAS/Abilities/Character/Player/ChaseHand/BPGA_Player_ChaseHand_Throw.uasset
  Content/GAS/Effects/Character/Player/Attack/BPGE_Player_BaseAttackDamage.uasset
  Content/GAS/Effects/CustomCalculations/CC_KnockBack_Collide_Damage_Causer.uasset
  Content/GAS/Effects/CustomCalculations/CC_KnockBack_Collide_Damage_Target.uasset
  Plugins/BlueprintRetarget/Binaries/Win64/UnrealEditor-BlueprintRetarget.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
  Plugins/KawaiiPhysics/Binaries/Win64/UnrealEditor-KawaiiPhysics.dll
  Plugins/KawaiiPhysics/Binaries/Win64/UnrealEditor-KawaiiPhysicsEd.dll
  Plugins/LDAssistant/Binaries/Win64/UnrealEditor-LDAssistant.dll
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
  Source/Project_LLL/Private/Entity/Object/Interactive/Gate/LLL_GateObject.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Base/LLL_CharacterGameplayAbilityBase.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/ChaseSystem/LLL_PGA_ControlChaseHand.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/LLL_PGA_AttackBase.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/LLL_PGA_AttackHitCheck.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/LLL_PGA_KnockBack.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/LLL_PGA_KnockBackCollisionCheck.cpp
  Source/Project_LLL/Private/GAS/CustomCalculations/LLL_CC_KnockBackDamageCalculate.cpp
  Source/Project_LLL/Public/Constant/LLL_GameplayTags.h
  Source/Project_LLL/Public/Constant/LLL_MeshSocketName.h
  Source/Project_LLL/Public/GAS/Ability/Character/Base/LLL_CharacterGameplayAbilityBase.h
  Source/Project_LLL/Public/GAS/Ability/Character/Player/ChaseSystem/LLL_PGA_ControlChaseHand.h
  Source/Project_LLL/Public/GAS/Ability/Character/Player/LLL_PGA_AttackBase.h
  Source/Project_LLL/Public/GAS/Ability/Character/Player/LLL_PGA_AttackHitCheck.h
  Source/Project_LLL/Public/GAS/Ability/Character/Player/LLL_PGA_KnockBack.h
  Source/Project_LLL/Public/GAS/Ability/Character/Player/LLL_PGA_KnockBackCollisionCheck.h
  Source/Project_LLL/Public/GAS/Attribute/Character/Player/LLL_PlayerCharacterAttributeSet.h
  Source/Project_LLL/Public/GAS/CustomCalculations/LLL_CC_KnockBackDamageCalculate.h
  Source/Project_LLL/Public/Util/LLL_MathHelper.h
Labels: enhancement, materialization

#160 [#145] UI 리소스 적용
  .vsconfig
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/Blueprints/UI/Monster/WBP_MonsterStatusWidget.uasset
  Content/Blueprints/UI/Player/WBP_ControlGuideWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerChaseActionWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerComboWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerGoldWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerStatusWidget.uasset
  Content/DataAsset/DA_Player.uasset
  Content/Materials/Instances/M_UI_CircleProgressBer_Inst.uasset
  Content/Materials/MasterMaterials/M_UI_CircleProgressBer.uasset
  Content/Materials/PostProcess/Base/PPM_LowHP.uasset
  Content/Materials/PostProcess/PPMI_LowHP.uasset
  Content/Materials/UI/Base/MI_UI_ShieldBar.uasset
  Content/Materials/UI/Base/M_UI_CircleProgressBer.uasset
  Content/Materials/UI/Base/M_UI_HPBar.uasset
  Content/Materials/UI/MI_UI_CircleProgressBer.uasset
  Content/Textures/Enviroments/T_LowHP_Noise.uasset
  Content/Textures/UI/T_ChaseGaugeBG.uasset
  Content/Textures/UI/T_ChaseGaugeFill.uasset
  Content/Textures/UI/T_Coin.uasset
  Content/Textures/UI/T_EnforceBG.uasset
  Content/Textures/UI/T_EnforceFill1.uasset
  Content/Textures/UI/T_EnforceFill2.uasset
  Content/Textures/UI/T_EnforceFill3.uasset
  Content/Textures/UI/T_HealthGauge.uasset
  Content/Textures/UI/T_PlayerRewardBG.uasset
  Content/Textures/UI/T_PlayerStatusBG.uasset
  Content/Textures/UI/T_PlayerStatusDeco.uasset
  Content/Textures/UI/T_SkillGauge.uasset
  Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerBase.cpp
  Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerUIManager.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/ComboSystem/LLL_PGA_ComboManagement.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Base/LLL_CharacterStatusWidget.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Monster/LLL_MonsterStatusWidget.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Player/LLL_PlayerChaseActionWidget.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Player/LLL_PlayerComboWidget.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Player/LLL_PlayerStatusWidget.cpp
  Source/Project_LLL/Public/Constant/LLL_FilePath.h
  Source/Project_LLL/Public/DataAsset/LLL_PlayerBaseDataAsset.h
  Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerBase.h
  Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerUIManager.h
  Source/Project_LLL/Public/UI/Entity/Character/Base/LLL_CharacterStatusWidget.h
  Source/Project_LLL/Public/UI/Entity/Character/Monster/LLL_MonsterStatusWidget.h
  Source/Project_LLL/Public/UI/Entity/Character/Player/LLL_PlayerChaseActionWidget.h
  Source/Project_LLL/Public/UI/Entity/Character/Player/LLL_PlayerComboWidget.h
  Source/Project_LLL/Public/UI/Entity/Character/Player/LLL_PlayerStatusWidget.h
Labels: enhancement, materialization

#161 [#2] develop 브랜치 메인으로 병합2
  .vsconfig
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/Blueprints/UI/Monster/WBP_MonsterStatusWidget.uasset
  Content/Blueprints/UI/Player/WBP_ControlGuideWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerChaseActionWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerComboWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerGoldWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerStatusWidget.uasset
  Content/DataAsset/DA_Player.uasset
  Content/Materials/Instances/M_UI_CircleProgressBer_Inst.uasset
  Content/Materials/MasterMaterials/M_UI_CircleProgressBer.uasset
  Content/Materials/PostProcess/Base/PPM_LowHP.uasset
  Content/Materials/PostProcess/PPMI_LowHP.uasset
  Content/Materials/UI/Base/MI_UI_ShieldBar.uasset
  Content/Materials/UI/Base/M_UI_CircleProgressBer.uasset
  Content/Materials/UI/Base/M_UI_HPBar.uasset
  Content/Materials/UI/MI_UI_CircleProgressBer.uasset
  Content/Textures/Enviroments/T_LowHP_Noise.uasset
  Content/Textures/UI/T_ChaseGaugeBG.uasset
  Content/Textures/UI/T_ChaseGaugeFill.uasset
  Content/Textures/UI/T_Coin.uasset
  Content/Textures/UI/T_EnforceBG.uasset
  Content/Textures/UI/T_EnforceFill1.uasset
  Content/Textures/UI/T_EnforceFill2.uasset
  Content/Textures/UI/T_EnforceFill3.uasset
  Content/Textures/UI/T_HealthGauge.uasset
  Content/Textures/UI/T_PlayerRewardBG.uasset
  Content/Textures/UI/T_PlayerStatusBG.uasset
  Content/Textures/UI/T_PlayerStatusDeco.uasset
  Content/Textures/UI/T_SkillGauge.uasset
  Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerBase.cpp
  Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerUIManager.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/ComboSystem/LLL_PGA_ComboManagement.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Base/LLL_CharacterStatusWidget.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Monster/LLL_MonsterStatusWidget.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Player/LLL_PlayerChaseActionWidget.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Player/LLL_PlayerComboWidget.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Player/LLL_PlayerStatusWidget.cpp
  Source/Project_LLL/Public/Constant/LLL_FilePath.h
  Source/Project_LLL/Public/DataAsset/LLL_PlayerBaseDataAsset.h
  Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerBase.h
  Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerUIManager.h
  Source/Project_LLL/Public/UI/Entity/Character/Base/LLL_CharacterStatusWidget.h
  Source/Project_LLL/Public/UI/Entity/Character/Monster/LLL_MonsterStatusWidget.h
  Source/Project_LLL/Public/UI/Entity/Character/Player/LLL_PlayerChaseActionWidget.h
  Source/Project_LLL/Public/UI/Entity/Character/Player/LLL_PlayerComboWidget.h
  Source/Project_LLL/Public/UI/Entity/Character/Player/LLL_PlayerStatusWidget.h
Labels: documentation

#173 [#171] 비동기 로딩 이슈 해결
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Config/DefaultGame.ini
  Source/Project_LLL/Private/System/Reward/LLL_RewardGimmick.cpp
  Source/Project_LLL/Public/GAS/Effect/LLL_ExtendedGameplayEffect.h
  Source/Project_LLL/Public/System/Reward/LLL_RewardGimmick.h
Labels: bug, hotfix

#178 [#138] n 데이터 전송 로직 구현
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/DataAsset/DA_PlayerThreateningDeath.uasset
  Content/GAS/Effects/Object/AbilityObject/BPGE_PhysicalProof_Attribute_Initialize.uasset
  Content/GAS/Effects/Object/AbilityObject/FeatherStorm/BPGE_FeatherStorm_InflictDamage.uasset
  Content/GAS/Effects/Object/AbilityObject/ThreateningDeath/BPGE_ThreateningDeath_Attribute_Initialize.uasset
  Content/Level/PrototypeLevel.umap
  Content/StarterContent/Architecture/Floor_400x400.uasset
  Source/Project_LLL/Private/Entity/Object/Ability/Base/LLL_AbilityObject.cpp
  Source/Project_LLL/Private/Entity/Object/Ability/LLL_PlayerFeatherStorm.cpp
  Source/Project_LLL/Private/Entity/Object/Ability/LLL_PlayerThreateningDeath.cpp
  Source/Project_LLL/Private/Entity/Object/Ability/LLL_Player_ThreateningDeath.cpp
  Source/Project_LLL/Private/Entity/Object/Base/LLL_BaseObject.cpp
  Source/Project_LLL/Private/Entity/Object/Thrown/Base/LLL_ThrownObject.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/RewardAbilitiesList/Base/LLL_PGA_RewardAbilityBase.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_FeatherBarrage.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_FeatherStorm.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_PersistentRevenge.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_ThreateningDeath.cpp
  Source/Project_LLL/Private/GAS/Attribute/Object/Skill/LLL_PlayerThreateningDeathAttributeSet.cpp
  Source/Project_LLL/Public/Constant/LLL_FilePath.h
  Source/Project_LLL/Public/DataAsset/LLL_PlayerThreateningDeathDataAsset.h
  Source/Project_LLL/Public/Entity/Object/Ability/Base/LLL_AbilityObject.h
  Source/Project_LLL/Public/Entity/Object/Ability/LLL_PlayerThreateningDeath.h
  Source/Project_LLL/Public/Entity/Object/Ability/LLL_Player_ThreateningDeath.h
  Source/Project_LLL/Public/Entity/Object/Base/LLL_BaseObject.h
  Source/Project_LLL/Public/Entity/Object/Thrown/Base/LLL_ThrownObject.h
  Source/Project_LLL/Public/GAS/Ability/Character/Player/RewardAbilitiesList/Base/LLL_PGA_RewardAbilityBase.h
  Source/Project_LLL/Public/GAS/Attribute/Object/Ability/LLL_PlayerThreateningDeathAttributeSet.h
  Source/Project_LLL/Public/GAS/Attribute/Object/Ability/LLL_ThreateningDeathAttributeSet.h
Labels: enhancement

#185 [#138] 이펙트 정지 로직 구현
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/Entity/Characters/Monster/MeleeMonster/ClawBasic/Animations/Montages/AM_ClawBasic_Attack.uasset
  Content/Entity/Characters/Monster/MeleeMonster/SwordDash/Animations/Montages/AM_SwordDash_Charge.uasset
  Content/Entity/Characters/Monster/MeleeMonster/SwordDash/Animations/Montages/AM_SwordDash_DashAttack.uasset
  Content/Entity/Characters/Monster/RangedMonster/StaffBasic/Animations/Montages/AM_StaffBasic_Attack.uasset
  Content/Entity/Characters/Monster/RangedMonster/StaffBasic/Animations/Montages/AM_StaffBasic_Charge.uasset
  Content/Entity/Characters/Player/Animations/Montages/AM_PlayerCharacter_BaseAttack.uasset
  Content/Entity/Characters/Player/Animations/Montages/AM_PlayerCharacter_Dash.uasset
  Content/Entity/Characters/Player/Animations/Montages/AM_PlayerCharacter_Dead.uasset
  Content/Entity/Characters/Player/Animations/Montages/AM_PlayerCharacter_RushAttack.uasset
  Content/GAS/Cues/Entity/Monster/MeleeMonster/SwordDash/BPGC_SwordDash_Dash.uasset
  Content/GAS/Cues/Entity/Player/BPGC_Player_BaseAttack_Hit1.uasset
  Content/GAS/Cues/Entity/Player/BPGC_Player_BaseAttack_Hit2.uasset
  Content/GAS/Cues/Entity/Player/BPGC_Player_BaseAttack_Hit3.uasset
  Content/GAS/Cues/Entity/Player/BPGC_Player_BaseAttack_Hit4.uasset
  Content/GAS/Cues/Entity/Player/BPGC_Player_ChaseAttack_Hit.uasset
  Source/Project_LLL/Private/AnimNotify/LLL_AnimNotify_FMod.cpp
  Source/Project_LLL/Private/AnimNotify/LLL_AnimNotify_GameplayTag.cpp
  Source/Project_LLL/Private/AnimNotify/LLL_AnimNotify_Niagara.cpp
  Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacter.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
  Source/Project_LLL/Private/Entity/Object/Base/LLL_BaseObject.cpp
  Source/Project_LLL/Private/Entity/Object/Thrown/Base/LLL_ThrownObject.cpp
  Source/Project_LLL/Private/GAS/Cue/LLL_GC_Base.cpp
  Source/Project_LLL/Private/System/Base/LLL_SystemBase.cpp
  Source/Project_LLL/Public/AnimNotify/LLL_AnimNotify_FMod.h
  Source/Project_LLL/Public/AnimNotify/LLL_AnimNotify_GameplayTag.h
  Source/Project_LLL/Public/AnimNotify/LLL_AnimNotify_Niagara.h
  Source/Project_LLL/Public/Entity/Character/Base/LLL_BaseCharacter.h
  Source/Project_LLL/Public/Entity/Object/Base/LLL_BaseObject.h
  Source/Project_LLL/Public/GAS/Cue/LLL_GC_Base.h
  Source/Project_LLL/Public/Interface/LLL_NiagaraInterface.h
  Source/Project_LLL/Public/System/Base/LLL_SystemBase.h
  Source/Project_LLL/Public/Util/LLL_NiagaraInfoStruct.h
Labels: bug, enhancement

#187 [#152] 이누리아 보상 개선, 문자열 테이블 및 이누리아 테이블 최신화, 플레이어 추격 액션 벽 통과 관련 수정
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Config/DefaultEngine.ini
  Content/DataTable/DT_AbilityData.uasset
  Content/DataTable/MiscellaneousDatas/DT_StringData.uasset
  Content/GAS/Effects/Character/Player/RewardEffectsList/BPGE_Berserk.uasset
  Content/GAS/Effects/Character/Player/RewardEffectsList/BPGE_BloodStainedFist.uasset
  Content/GAS/Effects/Character/Player/RewardEffectsList/BPGE_FeatherBarrage.uasset
  Content/GAS/Effects/Character/Player/RewardEffectsList/BPGE_FeatherStorm.uasset
  Content/GAS/Effects/Character/Player/RewardEffectsList/BPGE_PersistentRevenge.uasset
  Content/GAS/Effects/Character/Player/RewardEffectsList/BPGE_ThreateningDeath.uasset
  Source/Project_LLL/Private/Game/LLL_AbilityManageSubSystem.cpp
  Source/Project_LLL/Private/System/Reward/LLL_RewardGimmick.cpp
  Source/Project_LLL/Public/DataTable/LLL_AbilityDataTable.h
  Source/Project_LLL/Public/GAS/Effect/LLL_ExtendedGameplayEffect.h
  Source/Project_LLL/Public/System/Reward/LLL_RewardGimmick.h
Labels: enhancement

#188 [#138] 깃털 증폭 어빌리티 구현
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Config/DefaultEngine.ini
  Config/DefaultGameplayTags.ini
  Content/DataTable/DT_AbilityData.uasset
  Content/GAS/Abilities/Character/Player/RewardAbilitiesList/BPGA_FeatherBarrage.uasset
  Content/GAS/Abilities/Character/Player/RewardAbilitiesList/BPGA_PersistentRevenge.uasset
  Content/GAS/Effects/Character/Player/RewardEffectsList/BPGE_FeatherAmplification.uasset
  Content/Level/PrototypeLevel.umap
  Source/Project_LLL/Private/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_SpawnThrownObject.cpp
  Source/Project_LLL/Private/System/Reward/LLL_RewardGimmick.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Player/LLL_InventoryWidget.cpp
  Source/Project_LLL/Public/Constant/LLL_GameplayTags.h
  Source/Project_LLL/Public/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_SpawnThrownObject.h
Labels: bug, materialization

#194 [#176] 넉백관련 작업 및 UI 작업 병합
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/Blueprints/LD/BP_LD2BuildTest.uasset
  Content/Blueprints/LD/BP_LD7BuildTest.uasset
  Content/Blueprints/UI/Player/WBP_MainEruriaWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerInventoryWidget.uasset
  Content/Blueprints/UI/Reward/WBP_SelectRewardWidget.uasset
  Content/Blueprints/UI/System/Setting/WBP_MainSettingWidget.uasset
  Content/Blueprints/UI/System/Setting/WBP_SoundSettingWidget.uasset
  Content/Blueprints/UI/System/Title/WBP_TitleScreenWidget.uasset
  Content/Level/Design_Level/LD2Level.umap
  Content/Level/Design_Level/LD7Level.umap
  Content/Level/Design_Level/_GENERATED/hyeon2400/CubeGridToolOutput_EF483EBF.uasset
  Content/Level/PlayLevels/LV_Tutorial.umap
  Content/Level/ShaderTestLevel.umap
  Content/Materials/UI/Base/M_UI_EruriaRarityBar.uasset
  Content/Meshes/LevelDesign/SM_LD2_Wall.uasset
  Content/Textures/UI/InGame/T_EruriaRarity_A.uasset
  Content/Textures/UI/InGame/T_Eruria_UI_Background.uasset
  Content/Textures/UI/InGame/T_Eruria_UI_Background3.uasset
  Content/Textures/UI/InGame/T_Eruria_UI_Box_SizeUp.uasset
  Content/Textures/UI/InGame/T_PlayerRewardBG.uasset
  Content/Textures/UI/InGame/T_Player_Reward_Rare_A2.uasset
  Content/Textures/UI/InGame/T_Player_Reward_Round.uasset
  Content/Textures/UI/T_Blank.uasset
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
  Source/Project_LLL/Private/GAS/Ability/Character/Monster/LLL_MGA_SetFallableState.cpp
  Source/Project_LLL/Private/GAS/Task/LLL_AT_WaitOverlap.cpp
  Source/Project_LLL/Private/Game/LLL_GameInstance.cpp
  Source/Project_LLL/Private/System/MapGimmick/LLL_FallableWallGimmick.cpp
  Source/Project_LLL/Private/UI/System/LLL_TitleScreenWidget.cpp
  Source/Project_LLL/Public/Constant/LLL_CollisionChannel.h
  Source/Project_LLL/Public/GAS/Ability/Character/Monster/LLL_MGA_SetFallableState.h
  Source/Project_LLL/Public/GAS/Task/LLL_AT_WaitOverlap.h
  Source/Project_LLL/Public/System/MapGimmick/LLL_FallableWallGimmick.h
Labels: enhancement
