Repository Cr0ssEyE/Project_LLL, pull requests merged in 2024-04, with the labels that each got.

#90 [#89] 물리 적용
  Binaries/Win64/Project_LLLEditor.target
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/Entity/Characters/Player/ABP_Player.uasset
  Content/Entity/Characters/Player/Animations/Sequences/LLL_Riged_CR_02_Armature_Armature_002_Armature_ArmatureAction_Armature_ArmatureAction.uasset
  Content/Entity/Characters/Player/Animations/Sequences/LLL_Riged_CR_02_Armature_Basic_ATKRD.uasset
  Content/Entity/Characters/Player/Animations/Sequences/LLL_Riged_CR_02_Armature_Basic_ATKRD_001.uasset
  Content/Entity/Characters/Player/Animations/Sequences/LLL_Riged_CR_02_Armature_Basic_RD.uasset
  Content/Entity/Characters/Player/Animations/Sequences/LLL_Riged_CR_02_Armature_Basic_atk1.uasset
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
Labels: documentation, materialization

#96 [#88] 맵 로직 연결 작업
  Binaries/Win64/Project_LLLEditor.target
  Content/Blueprints/MapTest/BP_MapTest1.uasset
  Content/Blueprints/MapTest/BP_MapTest2.uasset
  Content/Blueprints/MapTest/BP_MapTest3.uasset
  Content/Blueprints/MapTest/BP_MapTest4.uasset
  Content/DataAsset/DA_Map.uasset
  Content/Level/MapCreateLevel.umap
  Content/Sequences/SEQ_FadeIn.uasset
  Content/Sequences/SEQ_FadeOut.uasset
  Source/Project_LLL/Private/Entity/Object/Interactive/LLL_GateObject.cpp
  Source/Project_LLL/Private/System/MapGimmick/LLL_MapGimmick.cpp
  Source/Project_LLL/Project_LLL.Build.cs
  Source/Project_LLL/Public/Constant/LLL_CollisionChannel.h
  Source/Project_LLL/Public/DataAsset/LLL_MapDataAsset.h
  Source/Project_LLL/Public/Entity/Object/Interactive/LLL_GateObject.h
  Source/Project_LLL/Public/System/MapGimmick/LLL_MapGimmick.h
Labels: materialization

#108 [#3] 그래픽 리소스 브랜치 병합
  Content/Level/LD2Level.umap
  Content/Materials/Instances/MI_BillBoard_Unlit_Base.uasset
  Content/Materials/Instances/MI_BillBoard_lit_Base.uasset
  Content/Materials/Instances/MI_Branch.uasset
  Content/Materials/Instances/MI_Cloud_A.uasset
  Content/Materials/Instances/MI_Cloud_B.uasset
  Content/Materials/Instances/MI_Ground_A.uasset
  Content/Materials/Instances/MI_Ground_B.uasset
  Content/Materials/Instances/MI_Ground_C.uasset
  Content/Materials/Instances/MI_Mountain_A.uasset
  Content/Materials/Instances/MI_Mountain_B.uasset
  Content/Materials/Instances/MI_SkyTest.uasset
  Content/Materials/Instances/MI_WaterFall.uasset
  Content/Materials/MasterMaterials/M_BillBoard.uasset
  Content/Materials/MasterMaterials/M_BillBoard_Unlit.uasset
  Content/StarterContent/Architecture/Floor_400x400.uasset
  Content/StarterContent/Blueprints/Blueprint_CeilingLight.uasset
  Content/StarterContent/Materials/M_Ground_Gravel.uasset
  Content/Textures/BackGroundTest/T_BRANCH.uasset
  Content/Textures/BackGroundTest/T_CLOUD_A.uasset
  Content/Textures/BackGroundTest/T_CLOUD_B.uasset
  Content/Textures/BackGroundTest/T_GROUND_A.uasset
  Content/Textures/BackGroundTest/T_GROUND_B.uasset
  Content/Textures/BackGroundTest/T_GROUND_C.uasset
  Content/Textures/BackGroundTest/T_MOUNTAIN1.uasset
  Content/Textures/BackGroundTest/T_MOUNTAIN2.uasset
  Content/Textures/BackGroundTest/T_SkyTest.uasset
  Content/Textures/BackGroundTest/T_WATERFALL.uasset
  Content/VFX/Script/NMS_Controlable_LocalSpace.uasset
  Content/VFX/Script/NS_PCAtt_TestOnly.uasset
Labels: materialization

#111 UI 베이스 작업
  Binaries/Win64/Project_LLLEditor.target
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/Blueprints/UI/Player/WBP_PlayerChaseActionWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerComboWidget.uasset
  Content/Blueprints/UI/Player/WBP_PlayerGoldWidget.uasset
  Content/Blueprints/UI/System/WBP_DialogWidget.uasset
  Content/Blueprints/UI/System/WBP_GuideWidget.uasset
  Content/DataAsset/DA_PlayerGoldComponent.uasset
  Content/Level/MapCreateLevel.umap
  Content/Level/PrototypeLevel.umap
  Content/Materials/Instances/M_UI_CircleProgressBer_Inst.uasset
  Content/Materials/MasterMaterials/M_UI_CircleProgressBer.uasset
  Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerGoldComponent.cpp
  Source/Project_LLL/Private/Entity/Object/Interactive/LLL_RewardObject.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Player/LLL_PlayerChaseActionWidget.cpp
  Source/Project_LLL/Private/UI/Entity/Character/Player/LLL_PlayerGoldWidget.cpp
  Source/Project_LLL/Public/Constant/LLL_FilePath.h
  Source/Project_LLL/Public/DataAsset/LLL_GoldComponentDataAsset.h
  Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerGoldComponent.h
  Source/Project_LLL/Public/UI/Entity/Character/Player/LLL_PlayerChaseActionWidget.h
  Source/Project_LLL/Public/UI/Entity/Character/Player/LLL_PlayerGoldWidget.h
Labels: enhancement, materialization

#115 [#114] BT 긴급 수정
  Binaries/Win64/Project_LLLEditor.target
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudio.dll
  Plugins/FMODStudio/Binaries/Win64/UnrealEditor-FMODStudioEditor.dll
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBaseAIController.cpp
Labels: bug, hotfix

#116 [#3] 그래픽 리소스 브랜치 작업물 병합
  Content/Level/ShaderTestLevel.umap
  Content/Materials/Instances/MI_BillBoard_Unlit_Base.uasset
  Content/Materials/Instances/MI_Test.uasset
  Content/Materials/MasterMaterials/M_BillBoard_Unlit.uasset
  Content/Materials/PostProcess/Base/PPM_AlignScreenPosition.uasset
  Content/Materials/PostProcess/Base/PPM_AlignScreenPosition_Inst.uasset
  Content/Materials/PostProcess/Base/Rectangle_C73AB1B6.uasset
  Content/Meshes/TestOnlyMeshes/Box_D129F25F.uasset
  Content/Textures/MiddleGroundTest/T_AcrhEntrance.uasset
Labels: materialization

#123 [#3] 레벨 환경 설정용 BP 추가
  Content/Blueprints/System/BP_EnviromentSetting.uasset
Labels: materialization

#124 [#4] 디자이너 브랜치 작업물 병합
  Config/DefaultGameplayTags.ini
  Content/DataAsset/DA_Player.uasset
  Content/DataTable/LD4.uasset
  Content/Entity/Characters/Player/Animations/Montage/AS_PlayerCharacter_BaseAttack.uasset
  Content/GAS/Abilities/Player/Attack/BPGA_Player_Attack_HitCheck_4.uasset
  Content/GAS/Abilities/Player/Attack/BPGA_Player_KnockBack.uasset
  Content/GAS/Abilities/Player/Attack/BPGA_Player_KnockBack_1.uasset
  Content/GAS/Abilities/Player/Attack/BPGA_Player_KnockBack_2.uasset
  Content/GAS/Abilities/Player/Attack/BPGA_Player_KnockBack_3.uasset
  Content/GAS/Abilities/Player/Attack/BPGA_Player_KnockBack_4.uasset
  Content/GAS/Effects/Character/Player/BPGE_Player_Attribute_Initialize.uasset
  Content/GAS/Effects/Object/ThrownObject/ChaseHand/BPGE_ChaseHand_Attribute_Initialize.uasset
  Content/Level/Design_Level/LD4Level.umap
  Source/Project_LLL/Public/Util/LLL_MathHelper.h
Labels: enhancement, materialization

#126 [#109] 코드 정리
  Binaries/Win64/Project_LLLEditor.target
  Binaries/Win64/UnrealEditor-Project_LLL.dll
  Content/Entity/Characters/Monster/BT_SwordDash.uasset
  Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacter.cpp
  Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
  Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerBase.cpp
  Source/Project_LLL/Private/GAS/Ability/Player/LLL_PGA_AttackBase.cpp
  Source/Project_LLL/Public/Entity/Character/Base/LLL_BaseCharacter.h
  Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerBase.h
Labels: enhancement
